package com.nevis.search.store;

import com.nevis.search.dto.ClientResponse;
import com.nevis.search.dto.CreateClientRequest;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

import java.util.List;

/** Writes and existence checks for clients. */
@Repository
public class ClientStore {

    private final JdbcClient jdbc;

    ClientStore(JdbcClient jdbc) {
        this.jdbc = jdbc;
    }

    /**
     * Inserts a client and returns it as stored.
     *
     * <p>RETURNING rather than a second SELECT: the id and any column default are generated by
     * the database, and reading them back in the same statement avoids a round trip and a race.
     */
    public ClientResponse insert(CreateClientRequest request) {
        String sql = """
                INSERT INTO clients (first_name, last_name, email, description, social_links)
                VALUES (:firstName, :lastName, :email, :description, :socialLinks)
                RETURNING id, first_name, last_name, email, description, social_links
                """;

        return jdbc.sql(sql)
                .param("firstName", request.firstName())
                .param("lastName", request.lastName())
                .param("email", request.email())
                .param("description", request.description())
                .param("socialLinks", request.socialLinks() == null
                        ? new String[0]
                        : request.socialLinks().toArray(String[]::new))
                .query((rs, rowNum) -> new ClientResponse(
                        rs.getString("id"),
                        rs.getString("first_name"),
                        rs.getString("last_name"),
                        rs.getString("email"),
                        rs.getString("description"),
                        rs.getArray("social_links") == null
                                ? List.of()
                                : List.of((String[]) rs.getArray("social_links").getArray())))
                .single();
    }

    /** Whether a client exists. Returns false for a malformed id rather than failing. */
    public boolean exists(String id) {
        return jdbc.sql("SELECT count(*) FROM clients WHERE id = CAST(:id AS uuid)")
                .param("id", id)
                .query(Integer.class)
                .single() > 0;
    }
}
